# Generated by Django 4.2.2 on 2023-11-16 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('test_score', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('interview_score', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('predictions', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Hepatite_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('sex', models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0)),
                ('steroide', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('antiviraux', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('fatigue', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('naevi', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('varices', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('ascite', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('bilirubine', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('phostate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('sgot', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('albumin', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('protime', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('histology', models.PositiveIntegerField(choices=[(0, 'Oui'), (1, 'Non')], default=0)),
                ('predictions', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
